### ISSUE TITLE
NoClassDefFoundError (instantiation / static constructor) exceptions are still not printed

### ISSUE THREAD

**Issue by RichardBradley** [etorreborre/specs2#403] opened 2015-07-29 13:26 UTC
Previously on this topic:
 * #281
  * https://github.com/etorreborre/specs2/commit/cfd715ff373bdfa8f7914e382d5ef669178c6acf
 * #387
  * https://github.com/etorreborre/specs2/commit/370bff3c81941365a28aa281d27e6086f5fe36b2

I still find it very difficult to diagnose test failures when using Specs2 and a test fails during class instantiation.

The underlying JVM mechanics don't help here because when a static constructor fails, only the very first such exception will contain a meaningful stack trace. All subsequent attempts to load the class will throw a `NoClassDefFoundError` with message "Could not initialize class X" without any cause.

Therefore it is essential that Specs2 logs the full stack trace for the very first exception when failing to initialise a test class. Currently, it is logging only one of the second or subsequent exceptions, meaning that I am unable to diagnose the problem.

Here's an example (source at https://gist.github.com/RichardBradley/d350ed973ecf7617be50 ):

```
object MyObject {

  val theNumber = {
    if (System.currentTimeMillis() > 0)
      throw new Exception(
        "The problem was foo. " +
          "This exception message really needs to be logged!")

    42
  }
}

class MySpec extends org.specs2.mutable.Specification {
  "MyObject" should {
    "compute the number" in {
      MyObject.theNumber === 42
    }
  }
}
```

The output from `sbt test` is (tested with 3.6.3 91731000f):

```
[info] MySpec
[info]
[info] MyObject should
[error]   ! compute the number
[error]    java.lang.ExceptionInInitializerError: Fatal execution error, caused by null (ExampleTest.scala:18)
[error] MySpec$$anonfun$1$$anonfun$apply$2$$anonfun$apply$3.apply(ExampleTest.scala:18)
[error] MySpec$$anonfun$1$$anonfun$apply$2$$anonfun$apply$3.apply(ExampleTest.scala:18)
[error] MySpec$$anonfun$1$$anonfun$apply$2.apply(ExampleTest.scala:18)
[error] MySpec$$anonfun$1$$anonfun$apply$2.apply(ExampleTest.scala:18)
[error] MyObject$.<init>(ExampleTest.scala:7)
[error] MyObject$.<clinit>(ExampleTest.scala)
[error] MySpec$$anonfun$1$$anonfun$apply$2$$anonfun$apply$3.apply(ExampleTest.scala:18)
[error] MySpec$$anonfun$1$$anonfun$apply$2$$anonfun$apply$3.apply(ExampleTest.scala:18)
[error] MySpec$$anonfun$1$$anonfun$apply$2.apply(ExampleTest.scala:18)
[error] MySpec$$anonfun$1$$anonfun$apply$2.apply(ExampleTest.scala:18)
[info]
[info]
[info] Total for specification MySpec
[info] Finished in 22 ms
[info] 1 example, 0 failure, 1 error
[info]
[error] Error: Total 1, Failed 0, Errors 1, Passed 0
[error] Error during tests:
[error]         MySpec
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 6 s, completed 29-Jul-2015 14:17:58
```

Notice that this doesn't contain the underlying exception message ("foo" in this example) anywhere. I think that `specs2` should print the message in this case.

The exception message is available in `target`, if you know exactly where to look:

```
$ grep foo -r target/
Binary file target/scala-2.11/classes/MyObject$.class matches
Binary file target/scala-2.11/test-classes/MyObject$.class matches
target/test-reports/MySpec.xml:Caused by: java.lang.Exception: The problem was foo. This exception message really needs to be logged!
```

I believe that the problem is that `specs2` attempts to construct the class twice, and the exception message from the second attempt is printed (more clearly now, thanks to the previous fixes linked above). However, the JVM will only include the cause details of static initializer exceptions on the first attempt, so we get a message "null" from `specs2`.

I might be able to have a go at fixing this some time in the next couple of weeks. I'll update here if so.

Thanks,

Rich

**Comment by etorreborre** [comment] 2015-07-30 02:01
With the latest commit your specification will display the "foo" message as well in the sbt console. I need to check what happens if a similar error happens when instantiating the spec itself.

**Comment by etorreborre** [comment] 2015-07-30 02:03
It looks like this spec
```
class TestMutableSpec extends mutable.Specification {
  val a = MyObject.theNumber
  "MyObject" should {
    "compute the number" in {
      MyObject.theNumber === 42
    }
  }
}
```
will display the cause as well.

**Comment by etorreborre** [comment] 2015-07-30 02:43
Available as `3.6.3-20150730014533-9773242` if you want to test it.

**Comment by RichardBradley** [comment] 2015-07-30 09:35
(Actually, on a second look at that example, it doesn't obviously use the "MyObject" in the constructor for "MySpec". I might have isolated a very similar but distinct bug here. I'll recheck if my complex example is fixed by the fix to this simple example when we have one.)

**Comment by etorreborre** [comment] 2015-07-30 11:14
So I can close?

**Comment by RichardBradley** [comment] 2015-07-30 11:14
I'm just testing now.

**Comment by RichardBradley** [comment] 2015-07-30 11:17
> Available as 3.6.3-20150730014533-9773242 if you want to test it.

Where? That's not on `https://repo1.maven.org/maven2`. 

The install instructions in the README could do with clarification on this point. They don't say how to add `specs2` to a project since you changed the versioning system. I can do a "publishLocal", but that generates a different version number to that you listed.

**Comment by etorreborre** [comment] 2015-07-30 11:22
Sorry I had a publishing issue and the real version is `https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-core_2.11/3.6.3-20150730025428-8b0c3e5/`. This will be incorporated in the next official release which will be `3.6.4`.

**Comment by RichardBradley** [comment] 2015-07-30 11:47
re install instructions, is there a way in the new system to get all of specs2 in a single requirement?
I previously had 
```
"org.specs2" %% "specs2" % "2.4.15"
```

Do I now need to list "specs2-core", "specs2-mock" etc. etc.?

**Comment by etorreborre** [comment] 2015-07-30 12:08
Yes in the `3.x` series the idea is to use finer-grained jars like `specs2-core`, `specs2-junit`, `specs2-scalacheck`,...

**Comment by RichardBradley** [comment] 2015-07-30 12:49
I'm having trouble upgrading my app to 3 to retest this.
Is there an upgrade guide?
I can't figure out how to get an implicit "ExecutionEnv" available in my Scope to use a FutureMatcher.

**Comment by RichardBradley** [comment] 2015-07-30 12:57
Do I have to wrap all my specs in a block like ```def is(implicit ee: ExecutionEnv) = {``` ? That's going to be very disruptive.

https://etorreborre.github.io/specs2/guide/SPECS2-3.6.3/org.specs2.guide.ExecutionEnvironments.html

I'll see if I can hack something up to do this testing

**Comment by RichardBradley** [comment] 2015-07-30 13:04
(I've found a workaround -- I'm already wrapping FutureMatchable to tweak the timeout re #348. I have changed my wrapper to require an implicit ExecutionContext (which I always have lying around, as it's an Akka Actor app), and use that to wrap up a ExecutionEnv which can satisfy FutureMatchable. 
The alternative of reworking all my 1000s of specs to a new structure would take far longer.)

**Comment by RichardBradley** [comment] 2015-07-30 16:21
Well, that was a difficult upgrade. 
``` 56 files changed, 325 insertions(+), 356 deletions(-)```
(Mostly related to removing the implicit "ExecutionContext" from Specification, which we relied on quite heavily.)

I can confirm that this fixes my big test as well as the simplified test posted above. Thanks very much! :-)

**Closed** 2015-07-30 16:29 UTC
