### ISSUE TITLE
resource not found on classpath in 3.8.9

### ISSUE THREAD

**Issue by puffnfresh** [etorreborre/specs2#576] opened 2017-05-12 04:15 UTC
Hey Eric, we've found a bug in specs2 introduced around 3.8.9

We have a resource we're trying to require and it's not being found:

```
[error] CAUSED BY
[error]  java.io.IOException: resource not found on classpath: test.conf (Parseable.java:735)
[error] com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:735)
[error] com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:710)
[error] com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
[error] com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
[error] com.typesafe.config.impl.Parseable.parse(Parseable.java:152)
[error] com.typesafe.config.impl.SimpleIncluder.fromBasename(SimpleIncluder.java:172)
[error] com.typesafe.config.impl.ConfigImpl.parseResourcesAnySyntax(ConfigImpl.java:132)
[error] com.typesafe.config.ConfigFactory.parseResourcesAnySyntax(ConfigFactory.java:978)
[error] com.typesafe.config.ConfigFactory.load(ConfigFactory.java:114)
[error] kadai.config.ConfigurationInstances.load(Configuration.scala:77)
[error] kadai.config.ConfigurationInstances.load$(Configuration.scala:74)
[error] kadai.config.Configuration$.load(Configuration.scala:242)
[error] kadai.config.ConfigurationSpec$$anon$1.delayedEndpoint$kadai$config$ConfigurationSpec$$anon$1$1(ConfigurationSpec.scala:163)
[error] kadai.config.ConfigurationSpec$$anon$1$delayedInit$body.apply(ConfigurationSpec.scala:162)
[error] kadai.test.SysProp.around(SystemProperties.scala:13)
[error] kadai.test.SysProp.delayedInit(SystemProperties.scala:8)
[error] kadai.config.ConfigurationSpec$$anon$1.<init>(ConfigurationSpec.scala:162)
[error] kadai.config.ConfigurationSpec$.$anonfun$new$134(ConfigurationSpec.scala:162)
```

The project is [Kadai](https://bitbucket.org/atlassian/kadai). You can see the full build output here:

https://bitbucket.org/atlassian/kadai/addon/pipelines/home#!/results/branch/fsalbaroli%252Fbump-dependencies/page/1

Here's the commit where we revert the upgrade to specs2:

https://bitbucket.org/atlassian/kadai/commits/b390bed675c1bbcd0f6a22c2ac9b3f3d0c0fc729?at=master

You should be able to check that out and reproduce by reverting it.

**Comment by etorreborre** [comment] 2017-05-12 05:59
It might be related to #556 (scroll to the end of the comments) where the fix I made was to set the context classloader before each execution. I will try without this fix and see if your issue disappears. If that's the case I will still have to understand what the right way to fix both issues at the same time :-).

**Comment by etorreborre** [comment] 2017-05-12 06:26
Yes I confirm that this is the problem. I'll try to find a way to fix it.

**Comment by etorreborre** [comment] 2017-05-12 20:57
This is really annoying because this bug doesn't seem to be deterministic. Now I can't reproduce it anymore :-(.

**Comment by etorreborre** [comment] 2017-05-19 16:17
I had a quick look at that again today and unfortunately I can't reproduce. I have added a command-line option to disable the use of sbt custom class loader:
```
sbt> testOnly -- !useCustomClassLoader
```
I will publish a release for you to test this week-end.

**Comment by puffnfresh** [comment] 2017-05-20 03:26
Thanks @etorreborre!

**Comment by etorreborre** [comment] 2017-05-22 13:26
Unfortunately I did some more tests with this new option and I still get the bug, ... sometimes. I need to spend more time to understand what's shaky with sbt and class loaders.

**Comment by etorreborre** [comment] 2017-05-22 22:12
@puffnfresh my fix doesn't seem to be working however I can suggest a workaround which will work regardless of the specs2 version. In `ConfigurationSpec.scala`
```scala
  "Loading from classpath" should {
    "not fail if the resource is existing" in {
      loadConf |> (_[String]("thing.id") must be equalTo "667")
    }

    "fail if the resource is not existing" in {
      Configuration.load("nosuchfile.conf") must throwA[com.typesafe.config.ConfigException.IO]
    }
    "support variable substitution" in {
      loadConf |> {
        _[String]("config.embed.more.thevar") must be equalTo "something to substitute"
      }
    }
  }

  "System properties" should {
    "override when loading from the Classpath" in new test.SysProp("thing.id", "666") {
      loadConf |> (_[String]("thing.id") must be equalTo "666")
    }

    "override when loading from a file" in new test.SysProp("thing.id", "666") {
      Configuration.from(file) |> (_[String]("thing.id") must be equalTo "666")
    }
  }

  def loadConf: Configuration = {
    Thread.currentThread.setContextClassLoader(getClass.getClassLoader)
    Configuration.load("test.conf")
  }
```

**Comment by puffnfresh** [comment] 2017-05-25 00:58
Thanks @etorreborre!

**Comment by etorreborre** [comment] 2017-06-06 06:40
I am closing this for now. I will follow-up with the sbt team to try to understand what is going on with classloaders.

**Closed by etorreborre** 2017-06-06 06:40 UTC

**Comment by etorreborre** [comment] 2017-06-06 06:44
sbt issue created [here](https://github.com/sbt/sbt/issues/3249).
