### ISSUE TITLE
Not implemented exceptions are truncated

### ISSUE THREAD

**Issue by samthebest** [etorreborre/specs2#454] opened 2016-02-07 12:44 UTC
When I have a `???` in my code, Specs2 somehow truncates the stacktrace so I have no idea how that line is being called, all I see is `an implementation is missing (MyClass.scala:95)`.

I've tried `-Dspecs2.fullstacktrace` but that didn't work.

**Comment by etorreborre** [comment] 2016-02-07 16:23
Can you please tell me which version of specs2 you are using and show me a small example of where this happens? In particular do you have `???` in the body of your class declaration, like:
```scala
class MySpec extends mutable.Specification {
  // to be set later
  val a = ???

  "first test" >> ok
}
```

**Comment by etorreborre** [comment] 2016-02-09 12:01
I actually cannot reproduce your case. Maybe you could try a more recent specs2 version and check if you get the same issue?

**Comment by etorreborre** [comment] 2016-03-07 16:07
I am closing this issue for now. Please reopen if a recent specs2 version (`> 3.7.2`) doesn't fix it.

**Closed by etorreborre** 2016-03-07 16:07 UTC
