### ISSUE TITLE
"Please report:" Internal specs2 exception thrown in Postgres configuration

### ISSUE THREAD

**Issue by zbeckman** [etorreborre/specs2#377] opened 2015-05-13 21:53 UTC
I have a test app that works fine with an H2 in-memory database. Now I'm trying to connect it to our real database. I'm either getting an internal Slick exception, or a "No suitable driver" exception, depending on my approach.

One of the exceptions states "Please report it with the preceding stacktrace at http://github.com/etorreborre/specs2/issues," so I'm doing that...

In regard to how to trigger this, here are the details:

The database configuration is:
```
db.edb = {
    driver = org.postgresql.Driver
    url = "jdbc:postgresql://db-server-1.hyrax.com:5444/CI_0"
    user = "xxx" // masked to protect the innocent
    password = "xxx" // masked to protect the innocent
    keepAliveConnection = true
}
```
My build.sbt has:
```
"org.postgresql" % "postgresql" % "9.4-1201-jdbc41",
```
The test itself (at this stage) is pretty simple:
```
		"The glimple data model classes" should {
			"insert a glimple row in the database" in {
				val db = Database.forConfig("db.edb") // works with db.h2mem1
				val glimples = TableQuery[GPGlimpleModel]

				val insertGlimples = db.run(glimples += GPGlimple(None, None, 1, true, true, 1))

				val count = Await.result(insertGlimples, Duration.Inf)

				println(count)
				count must beEqualTo(1)
				...
```

Here's the full stack trace:

[error] java.lang.NoClassDefFoundError: com/zaxxer/hikari/HikariConfig
[error]   caused by java.lang.ClassNotFoundException: com.zaxxer.hikari.HikariConfig
[error]
[error] STACKTRACE
[error]   slick.jdbc.HikariCPJdbcDataSource$.forConfig(JdbcDataSource.scala:141)
[error]   slick.jdbc.HikariCPJdbcDataSource$.forConfig(JdbcDataSource.scala:135)
[error]   slick.jdbc.JdbcDataSource$.forConfig(JdbcDataSource.scala:35)
[error]   slick.jdbc.JdbcBackend$DatabaseFactoryDef$class.forConfig(JdbcBackend.scala:223)
[error]   slick.jdbc.JdbcBackend$$anon$3.forConfig(JdbcBackend.scala:33)
[error]   models.TestGlimpleModel$$anonfun$1$$anonfun$apply$64$$anonfun$apply$65.apply(TestGlimpleModel.scala:166)
[error]   models.TestGlimpleModel$$anonfun$1$$anonfun$apply$64$$anonfun$apply$65.apply(TestGlimpleModel.scala:158)
[error]   org.specs2.matcher.MatchResult$$anon$12$$anonfun$asResult$1.apply(MatchResult.scala:310)
[error]   org.specs2.matcher.MatchResult$$anon$12$$anonfun$asResult$1.apply(MatchResult.scala:310)
[error]   org.specs2.execute.ResultExecution$class.execute(ResultExecution.scala:25)
[error]   org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:120)
[error]   org.specs2.execute.Result$$anon$10.asResult(Result.scala:230)
[error]   org.specs2.execute.AsResult$.apply(AsResult.scala:25)
[error]   org.specs2.matcher.MatchResult$$anon$12.asResult(MatchResult.scala:310)
[error]   org.specs2.execute.AsResult$.apply(AsResult.scala:25)
[error]   org.specs2.main.CommandLineAsResult$$anon$1.asResult(CommandLineAsResult.scala:17)
[error]   org.specs2.main.CommandLineAsResult$$anonfun$apply$1.apply(CommandLineAsResult.scala:21)
[error]   org.specs2.main.CommandLineAsResult$$anonfun$apply$1.apply(CommandLineAsResult.scala:21)
[error]   org.specs2.specification.dsl.mutable.ExampleDsl1$BlockExample$$anonfun$$greater$greater$1.apply(ExampleDsl.scala:39)
[error]   org.specs2.specification.dsl.mutable.ExampleDsl1$BlockExample$$anonfun$$greater$greater$1.apply(ExampleDsl.scala:39)
[error]   org.specs2.specification.core.Execution$$anonfun$withEnv$1$$anonfun$apply$3.apply(Execution.scala:120)
[error]   org.specs2.execute.ResultExecution$class.execute(ResultExecution.scala:25)
[error]   org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:120)
[error]   org.specs2.execute.Result$$anon$10.asResult(Result.scala:230)
[error]   org.specs2.execute.AsResult$.apply(AsResult.scala:25)
[error]   org.specs2.specification.core.Execution$$anonfun$withEnv$1.apply(Execution.scala:120)
[error]   org.specs2.specification.core.Execution$$anonfun$withEnv$1.apply(Execution.scala:120)
[error]   org.specs2.specification.core.Execution$$anonfun$execute$2$$anonfun$apply$2.apply(Execution.scala:70)
[error]   org.specs2.specification.core.Execution$$anonfun$execute$2$$anonfun$apply$2.apply(Execution.scala:70)
[error]   org.specs2.specification.core.Execution.setResult(Execution.scala:76)
[error]   org.specs2.specification.core.Execution$$anonfun$execute$2.apply(Execution.scala:70)
[error]   org.specs2.specification.core.Execution$$anonfun$execute$2.apply(Execution.scala:70)
[error]   scala.Option.fold(Option.scala:158)
[error]   org.specs2.specification.core.Execution.execute(Execution.scala:70)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$executeFragment$1$$anonfun$apply$6.apply(Executor.scala:132)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$executeFragment$1$$anonfun$apply$6.apply(Executor.scala:130)
[error]   org.specs2.specification.core.Fragment.updateExecution(Fragment.scala:44)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$executeFragment$1.apply(Executor.scala:130)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$executeFragment$1.apply(Executor.scala:129)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$sequencedExecution$1.executedFragment$lzycompute$1(Executor.scala:104)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$sequencedExecution$1.org$specs2$specification$process$DefaultExecutor$class$$anonfun$$executedFragment$1(Executor.scala:104)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$sequencedExecution$1$$anonfun$3.apply(Executor.scala:109)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$sequencedExecution$1$$anonfun$3.apply(Executor.scala:109)
[error]   scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:272)
[error]   scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:272)
[error]   scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$4.apply(Task.scala:280)
[error]   scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$4.apply(Task.scala:280)
[error]   scalaz.concurrent.Task$.Try(Task.scala:385)
[error]   scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:280)
[error]   scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:280)
[error]   scalaz.concurrent.Future.step(Future.scala:111)
[error]   scalaz.concurrent.Future.listen(Future.scala:76)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2$$anonfun$apply$10.apply(Future.scala:310)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2$$anonfun$apply$10.apply(Future.scala:309)
[error]   scala.collection.Iterator$class.foreach(Iterator.scala:750)
[error]   scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
[error]   scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[error]   scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2.apply(Future.scala:309)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2.apply(Future.scala:305)
[error]   scalaz.concurrent.Future.listen(Future.scala:80)
[error]   scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:80)
[error]   scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:80)
[error]   scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
[error]   scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
[error]   scalaz.Free.resume(Free.scala:73)
[error]   scalaz.Free.go2$1(Free.scala:118)
[error]   scalaz.Free.go(Free.scala:122)
[error]   scalaz.Free.run(Free.scala:172)
[error]   scalaz.concurrent.Future.listen(Future.scala:77)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2$$anonfun$apply$10.apply(Future.scala:310)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2$$anonfun$apply$10.apply(Future.scala:309)
[error]   scala.collection.Iterator$class.foreach(Iterator.scala:750)
[error]   scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
[error]   scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[error]   scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2.apply(Future.scala:309)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2.apply(Future.scala:305)
[error]   scalaz.concurrent.Future.listen(Future.scala:80)
[error]   scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:80)
[error]   scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:80)
[error]   scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
[error]   scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
[error]   scalaz.Free.resume(Free.scala:73)
[error]   scalaz.Free.go2$1(Free.scala:118)
[error]   scalaz.Free.go(Free.scala:122)
[error]   scalaz.Free.run(Free.scala:172)
[error]   scalaz.concurrent.Future.listen(Future.scala:77)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2$$anonfun$apply$10.apply(Future.scala:310)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2$$anonfun$apply$10.apply(Future.scala:309)
[error]   scala.collection.Iterator$class.foreach(Iterator.scala:750)
[error]   scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
[error]   scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[error]   scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2.apply(Future.scala:309)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2.apply(Future.scala:305)
[error]   scalaz.concurrent.Future.listen(Future.scala:80)
[error]   scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:80)
[error]   scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:80)
[error]   scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
[error]   scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
[error]   scalaz.Free.resume(Free.scala:73)
[error]   scalaz.Free.go2$1(Free.scala:118)
[error]   scalaz.Free.go(Free.scala:122)
[error]   scalaz.Free.run(Free.scala:172)
[error]   scalaz.concurrent.Future.listen(Future.scala:77)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2$$anonfun$apply$10.apply(Future.scala:310)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2$$anonfun$apply$10.apply(Future.scala:309)
[error]   scala.collection.Iterator$class.foreach(Iterator.scala:750)
[error]   scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
[error]   scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[error]   scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2.apply(Future.scala:309)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2.apply(Future.scala:305)
[error]   scalaz.concurrent.Future.listen(Future.scala:80)
[error]   scalaz.concurrent.Future.runAsync(Future.scala:143)
[error]   scalaz.concurrent.Future.run(Future.scala:160)
[error]   scalaz.concurrent.Task.attemptRun(Task.scala:104)
[error]   org.specs2.control.ActionT$.fromTask(ActionT.scala:125)
[error]   org.specs2.control.ActionTSupport$class.fromTask(ActionT.scala:188)
[error]   org.specs2.control.package$Actions$.fromTask(package.scala:29)
[error]   org.specs2.reporter.Reporter$$anonfun$report$1.apply(Reporter.scala:47)
[error]   org.specs2.reporter.Reporter$$anonfun$report$1.apply(Reporter.scala:37)
[error]   org.specs2.runner.SbtRunner$$anonfun$specificationRun$1$$anonfun$2.apply(SbtRunner.scala:75)
[error]   org.specs2.runner.SbtRunner$$anonfun$specificationRun$1$$anonfun$2.apply(SbtRunner.scala:75)
[error]   org.specs2.control.ActionT$$anonfun$flatMap$1$$anonfun$apply$2.apply(ActionT.scala:36)
[error]   org.specs2.control.ActionT$$anonfun$flatMap$1$$anonfun$apply$2.apply(ActionT.scala:36)
[error]   org.specs2.control.StatusT$$anonfun$flatMap$1.apply(StatusT.scala:20)
[error]   org.specs2.control.StatusT$$anonfun$flatMap$1.apply(StatusT.scala:19)
[error]   scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
[error]   scalaz.WriterT$$anonfun$flatMapF$1.apply(WriterT.scala:63)
[error]   scalaz.WriterT$$anonfun$flatMapF$1.apply(WriterT.scala:62)
[error]   scalaz.effect.IO$$anonfun$flatMap$1$$anonfun$apply$9.apply(IO.scala:62)
[error]   scalaz.effect.IO$$anonfun$flatMap$1$$anonfun$apply$9.apply(IO.scala:61)
[error]   scalaz.Free$$anonfun$flatMap$1$$anonfun$apply$1.apply(Free.scala:60)
[error]   scalaz.Free$$anonfun$flatMap$1$$anonfun$apply$1.apply(Free.scala:60)
[error]   scalaz.Free.resume(Free.scala:72)
[error]   scalaz.Free.go2$1(Free.scala:118)
[error]   scalaz.Free.go(Free.scala:122)
[error]   scalaz.Free.run(Free.scala:172)
[error]   scalaz.effect.IO$class.unsafePerformIO(IO.scala:22)
[error]   scalaz.effect.IOFunctions$$anon$6.unsafePerformIO(IO.scala:227)
[error]   org.specs2.runner.SbtRunner$$anonfun$newTask$1$$anon$4.execute(SbtRunner.scala:40)
[error]   sbt.ForkMain$Run$2.call(ForkMain.java:294)
[error]   sbt.ForkMain$Run$2.call(ForkMain.java:284)
[error]   java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]   java.lang.Thread.run(Thread.java:745)
[error]
[error]   CAUSED BY java.lang.ClassNotFoundException: com.zaxxer.hikari.HikariConfig
[error]   java.net.URLClassLoader$1.run(URLClassLoader.java:372)
[error]   java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[error]   java.security.AccessController.doPrivileged(Native Method)
[error]   java.net.URLClassLoader.findClass(URLClassLoader.java:360)
[error]   java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error]   sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
[error]   java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error]   slick.jdbc.HikariCPJdbcDataSource$.forConfig(JdbcDataSource.scala:141)
[error]   slick.jdbc.HikariCPJdbcDataSource$.forConfig(JdbcDataSource.scala:135)
[error]   slick.jdbc.JdbcDataSource$.forConfig(JdbcDataSource.scala:35)
[error]   slick.jdbc.JdbcBackend$DatabaseFactoryDef$class.forConfig(JdbcBackend.scala:223)
[error]   slick.jdbc.JdbcBackend$$anon$3.forConfig(JdbcBackend.scala:33)
[error]   models.TestGlimpleModel$$anonfun$1$$anonfun$apply$64$$anonfun$apply$65.apply(TestGlimpleModel.scala:166)
[error]   models.TestGlimpleModel$$anonfun$1$$anonfun$apply$64$$anonfun$apply$65.apply(TestGlimpleModel.scala:158)
[error]   org.specs2.matcher.MatchResult$$anon$12$$anonfun$asResult$1.apply(MatchResult.scala:310)
[error]   org.specs2.matcher.MatchResult$$anon$12$$anonfun$asResult$1.apply(MatchResult.scala:310)
[error]   org.specs2.execute.ResultExecution$class.execute(ResultExecution.scala:25)
[error]   org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:120)
[error]   org.specs2.execute.Result$$anon$10.asResult(Result.scala:230)
[error]   org.specs2.execute.AsResult$.apply(AsResult.scala:25)
[error]   org.specs2.matcher.MatchResult$$anon$12.asResult(MatchResult.scala:310)
[error]   org.specs2.execute.AsResult$.apply(AsResult.scala:25)
[error]   org.specs2.main.CommandLineAsResult$$anon$1.asResult(CommandLineAsResult.scala:17)
[error]   org.specs2.main.CommandLineAsResult$$anonfun$apply$1.apply(CommandLineAsResult.scala:21)
[error]   org.specs2.main.CommandLineAsResult$$anonfun$apply$1.apply(CommandLineAsResult.scala:21)
[error]   org.specs2.specification.dsl.mutable.ExampleDsl1$BlockExample$$anonfun$$greater$greater$1.apply(ExampleDsl.scala:39)
[error]   org.specs2.specification.dsl.mutable.ExampleDsl1$BlockExample$$anonfun$$greater$greater$1.apply(ExampleDsl.scala:39)
[error]   org.specs2.specification.core.Execution$$anonfun$withEnv$1$$anonfun$apply$3.apply(Execution.scala:120)
[error]   org.specs2.execute.ResultExecution$class.execute(ResultExecution.scala:25)
[error]   org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:120)
[error]   org.specs2.execute.Result$$anon$10.asResult(Result.scala:230)
[error]   org.specs2.execute.AsResult$.apply(AsResult.scala:25)
[error]   org.specs2.specification.core.Execution$$anonfun$withEnv$1.apply(Execution.scala:120)
[error]   org.specs2.specification.core.Execution$$anonfun$withEnv$1.apply(Execution.scala:120)
[error]   org.specs2.specification.core.Execution$$anonfun$execute$2$$anonfun$apply$2.apply(Execution.scala:70)
[error]   org.specs2.specification.core.Execution$$anonfun$execute$2$$anonfun$apply$2.apply(Execution.scala:70)
[error]   org.specs2.specification.core.Execution.setResult(Execution.scala:76)
[error]   org.specs2.specification.core.Execution$$anonfun$execute$2.apply(Execution.scala:70)
[error]   org.specs2.specification.core.Execution$$anonfun$execute$2.apply(Execution.scala:70)
[error]   scala.Option.fold(Option.scala:158)
[error]   org.specs2.specification.core.Execution.execute(Execution.scala:70)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$executeFragment$1$$anonfun$apply$6.apply(Executor.scala:132)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$executeFragment$1$$anonfun$apply$6.apply(Executor.scala:130)
[error]   org.specs2.specification.core.Fragment.updateExecution(Fragment.scala:44)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$executeFragment$1.apply(Executor.scala:130)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$executeFragment$1.apply(Executor.scala:129)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$sequencedExecution$1.executedFragment$lzycompute$1(Executor.scala:104)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$sequencedExecution$1.org$specs2$specification$process$DefaultExecutor$class$$anonfun$$executedFragment$1(Executor.scala:104)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$sequencedExecution$1$$anonfun$3.apply(Executor.scala:109)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$sequencedExecution$1$$anonfun$3.apply(Executor.scala:109)
[error]   scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:272)
[error]   scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:272)
[error]   scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$4.apply(Task.scala:280)
[error]   scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$4.apply(Task.scala:280)
[error]   scalaz.concurrent.Task$.Try(Task.scala:385)
[error]   scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:280)
[error]   scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:280)
[error]   scalaz.concurrent.Future.step(Future.scala:111)
[error]   scalaz.concurrent.Future.listen(Future.scala:76)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2$$anonfun$apply$10.apply(Future.scala:310)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2$$anonfun$apply$10.apply(Future.scala:309)
[error]   scala.collection.Iterator$class.foreach(Iterator.scala:750)
[error]   scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
[error]   scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[error]   scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2.apply(Future.scala:309)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2.apply(Future.scala:305)
[error]   scalaz.concurrent.Future.listen(Future.scala:80)
[error]   scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:80)
[error]   scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:80)
[error]   scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
[error]   scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
[error]   scalaz.Free.resume(Free.scala:73)
[error]   scalaz.Free.go2$1(Free.scala:118)
[error]   scalaz.Free.go(Free.scala:122)
[error]   scalaz.Free.run(Free.scala:172)
[error]   scalaz.concurrent.Future.listen(Future.scala:77)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2$$anonfun$apply$10.apply(Future.scala:310)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2$$anonfun$apply$10.apply(Future.scala:309)
[error]   scala.collection.Iterator$class.foreach(Iterator.scala:750)
[error]   scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
[error]   scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[error]   scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2.apply(Future.scala:309)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2.apply(Future.scala:305)
[error]   scalaz.concurrent.Future.listen(Future.scala:80)
[error]   scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:80)
[error]   scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:80)
[error]   scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
[error]   scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
[error]   scalaz.Free.resume(Free.scala:73)
[error]   scalaz.Free.go2$1(Free.scala:118)
[error]   scalaz.Free.go(Free.scala:122)
[error]   scalaz.Free.run(Free.scala:172)
[error]   scalaz.concurrent.Future.listen(Future.scala:77)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2$$anonfun$apply$10.apply(Future.scala:310)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2$$anonfun$apply$10.apply(Future.scala:309)
[error]   scala.collection.Iterator$class.foreach(Iterator.scala:750)
[error]   scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
[error]   scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[error]   scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2.apply(Future.scala:309)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2.apply(Future.scala:305)
[error]   scalaz.concurrent.Future.listen(Future.scala:80)
[error]   scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:80)
[error]   scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:80)
[error]   scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
[error]   scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
[error]   scalaz.Free.resume(Free.scala:73)
[error]   scalaz.Free.go2$1(Free.scala:118)
[error]   scalaz.Free.go(Free.scala:122)
[error]   scalaz.Free.run(Free.scala:172)
[error]   scalaz.concurrent.Future.listen(Future.scala:77)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2$$anonfun$apply$10.apply(Future.scala:310)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2$$anonfun$apply$10.apply(Future.scala:309)
[error]   scala.collection.Iterator$class.foreach(Iterator.scala:750)
[error]   scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
[error]   scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[error]   scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2.apply(Future.scala:309)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2.apply(Future.scala:305)
[error]   scalaz.concurrent.Future.listen(Future.scala:80)
[error]   scalaz.concurrent.Future.runAsync(Future.scala:143)
[error]   scalaz.concurrent.Future.run(Future.scala:160)
[error]   scalaz.concurrent.Task.attemptRun(Task.scala:104)
[error]   org.specs2.control.ActionT$.fromTask(ActionT.scala:125)
[error]   org.specs2.control.ActionTSupport$class.fromTask(ActionT.scala:188)
[error]   org.specs2.control.package$Actions$.fromTask(package.scala:29)
[error]   org.specs2.reporter.Reporter$$anonfun$report$1.apply(Reporter.scala:47)
[error]   org.specs2.reporter.Reporter$$anonfun$report$1.apply(Reporter.scala:37)
[error]   org.specs2.runner.SbtRunner$$anonfun$specificationRun$1$$anonfun$2.apply(SbtRunner.scala:75)
[error]   org.specs2.runner.SbtRunner$$anonfun$specificationRun$1$$anonfun$2.apply(SbtRunner.scala:75)
[error]   org.specs2.control.ActionT$$anonfun$flatMap$1$$anonfun$apply$2.apply(ActionT.scala:36)
[error]   org.specs2.control.ActionT$$anonfun$flatMap$1$$anonfun$apply$2.apply(ActionT.scala:36)
[error]   org.specs2.control.StatusT$$anonfun$flatMap$1.apply(StatusT.scala:20)
[error]   org.specs2.control.StatusT$$anonfun$flatMap$1.apply(StatusT.scala:19)
[error]   scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
[error]   scalaz.WriterT$$anonfun$flatMapF$1.apply(WriterT.scala:63)
[error]   scalaz.WriterT$$anonfun$flatMapF$1.apply(WriterT.scala:62)
[error]   scalaz.effect.IO$$anonfun$flatMap$1$$anonfun$apply$9.apply(IO.scala:62)
[error]   scalaz.effect.IO$$anonfun$flatMap$1$$anonfun$apply$9.apply(IO.scala:61)
[error]   scalaz.Free$$anonfun$flatMap$1$$anonfun$apply$1.apply(Free.scala:60)
[error]   scalaz.Free$$anonfun$flatMap$1$$anonfun$apply$1.apply(Free.scala:60)
[error]   scalaz.Free.resume(Free.scala:72)
[error]   scalaz.Free.go2$1(Free.scala:118)
[error]   scalaz.Free.go(Free.scala:122)
[error]   scalaz.Free.run(Free.scala:172)
[error]   scalaz.effect.IO$class.unsafePerformIO(IO.scala:22)
[error]   scalaz.effect.IOFunctions$$anon$6.unsafePerformIO(IO.scala:227)
[error]   org.specs2.runner.SbtRunner$$anonfun$newTask$1$$anon$4.execute(SbtRunner.scala:40)
[error]   sbt.ForkMain$Run$2.call(ForkMain.java:294)
[error]   sbt.ForkMain$Run$2.call(ForkMain.java:284)
[error]   java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]   java.lang.Thread.run(Thread.java:745)
[error]
[error]
[error] This looks like a specs2 exception...
[error] Please report it with the preceding stacktrace at http://github.com/etorreborre/specs2/issues

**Comment by etorreborre** [comment] 2015-05-13 22:49
This looks like you are trying to instantiate a class, `com/zaxxer/hikari/HikariConfig` in the body of the `Specification` class, but it is not found. In that case an exception is thrown and the specification can not even be created. You certainly have a `val` somewhere with an expression trying to instantiate your `HikariConfig`. Transform that into a `lazy val` (to just get a normal specs2 error) and then try to fix your classpath and that should fix the problem.

**Comment by zbeckman** [comment] 2015-05-14 06:27
Definitely not in my Specification. The ENTIRE test is shown above, except for the import statements and other preamble.

I didn't even know what HikariCP was until today – apparently some kind of database cache. For now I have simply disabled it, but whatever the problem is, it's still there. Buried deep in the bowels of Play Framework, I suspect. Fortunately, by disabling the connection pooling it goes away... at least, until we want connection pooling... :-(

**Comment by etorreborre** [comment] 2015-05-14 06:34
Don't you inherit from a trait somewhere?

**Comment by etorreborre** [comment] 2015-05-14 22:18
Did you finally find the issue?

**Comment by zbeckman** [comment] 2015-05-14 23:09
The only classes I'm inheriting from:
```
class TestGlimpleModel extends PlaySpecification with ScalaCheck {
```
I haven't found it yet – you are probably right, some obscure class path problem in our system. But I've no idea where to begin, other than systematically removing components to see where we end up. I'm planning on working through it in the next day or two.

**Comment by etorreborre** [comment] 2015-07-20 22:29
Did you eventually solve this issue?

**Comment by etorreborre** [comment] 2015-08-10 23:09
I'm closing this issue for now until I can reproduce it somehow.

**Closed** 2015-09-15 22:21 UTC
