### ISSUE TITLE
Parallel tests run in batches

### ISSUE THREAD

**Issue by beaushinkle** [etorreborre/specs2#551] opened 2017-02-21 20:18 UTC
My specs appear to be running in batches.
```
class DummySpec extends Specification {

  val r = scala.util.Random

  def longTest(x: String)() = {
    val sleep = r.nextInt(10000) + 2000
    println("Running test " + x + " with timeout " + sleep + " msecs")
    Thread.sleep(sleep)
    println("done with " + x)
    ko(x)
  }

  override def is = {
    println("Running A Sample Of Regression Tests")
    (1 to 40).map(_.toString).foldLeft(Fragments(fragmentFactory.start))((fragments, test) => {
      fragments ^ ("Longtest" ! longTest(test))
    })
  }
}
```
produces this output:
```
Running A Sample Of Regression Tests
Running test 1 with timeout 9927 msecs
Running test 4 with timeout 3685 msecs
Running test 8 with timeout 3703 msecs
Running test 7 with timeout 3604 msecs
Running test 6 with timeout 5756 msecs
Running test 2 with timeout 10288 msecs
Running test 5 with timeout 5010 msecs
Running test 3 with timeout 11457 msecs
done with 7
Running test 9 with timeout 4855 msecs
done with 4
done with 8
done with 5
done with 6
done with 9
done with 1
done with 2
done with 3
Running test 11 with timeout 9427 msecs
Running test 13 with timeout 10141 msecs
Running test 14 with timeout 10196 msecs
Running test 10 with timeout 7744 msecs
Running test 16 with timeout 7280 msecs
Running test 17 with timeout 7462 msecs
Running test 12 with timeout 5377 msecs
Running test 15 with timeout 9943 msecs
done with 12
Running test 18 with timeout 6962 msecs
done with 16
done with 17
done with 10
done with 11
done with 15
done with 13
done with 14
done with 18
Running test 25 with timeout 5601 msecs
Running test 26 with timeout 6695 msecs
Running test 21 with timeout 4452 msecs
Running test 24 with timeout 7159 msecs
Running test 20 with timeout 6064 msecs
Running test 22 with timeout 8097 msecs
Running test 19 with timeout 9658 msecs
Running test 23 with timeout 5572 msecs
done with 21
Running test 27 with timeout 4038 msecs
done with 23
done with 25
done with 20
done with 26
done with 24
done with 22
done with 27
done with 19
Running test 29 with timeout 11074 msecs
Running test 34 with timeout 11885 msecs
Running test 32 with timeout 4849 msecs
Running test 30 with timeout 7297 msecs
Running test 33 with timeout 3205 msecs
Running test 31 with timeout 3849 msecs
Running test 28 with timeout 10158 msecs
Running test 35 with timeout 10630 msecs
done with 33
Running test 36 with timeout 6423 msecs
done with 31
done with 32
done with 30
done with 36
done with 28
done with 35
done with 29
done with 34
Running test 37 with timeout 8450 msecs
Running test 38 with timeout 6542 msecs
Running test 40 with timeout 11521 msecs
Running test 39 with timeout 4564 msecs
done with 39
done with 38
done with 37
done with 40
```
It looks like we pick up 8 tests at a time, generally wait for them all to be finished, then pick up the next batch of 8 tests and so on.

I found [Executor:137](https://github.com/etorreborre/specs2/blob/master/core/src/main/scala/org/specs2/specification/process/Executor.scala#L137-L142) which looks like it may be related.

Is this batching by design, or would you consider this a bug?

**Comment by etorreborre** [comment] 2017-02-21 21:45
This is by design so that the tests are executed concurrently but the results "flow" on screen in order. This could probably be improved but I don't know exactly how. Is that an issue for you?

**Comment by Shadowfiend** [comment] 2017-02-22 01:58
The issue we're running into (I'm working with @beaushinkle on this) is that we'll have a series of say 540 tests, where maybe 10% are long-running. If these are distributed throughout the run, they can cause serious bottlenecks. Since much of the spec is spent waiting on an external service, not having these batches would be tremendously helpful... and we may be willing to sacrifice ordering to get that behavior. Not sure if that makes it any easier to implement though :)

**Comment by etorreborre** [comment] 2017-02-22 08:01
@Shadowfiend @beaushinkle I am publishing a new version [`3.8.8-20170222075022-d6a08b0`](https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-core_2.12/3.8.8-20170222075022-d6a08b0) where you can use the `unbatched` argument (or `batchSize(n: Int)`) to control how many examples get executed at the time.

**Comment by etorreborre** [comment] 2017-02-22 08:31
BTW your specification can be written as
```scala
class DummySpec extends mutable.Specification {
  unbatched

  val r = scala.util.Random

  def longTest(x: String)() = {
    val sleep = r.nextInt(1000) + 200
    println("Running test " + x + " with timeout " + sleep + " msecs")
    Thread.sleep(sleep.toLong)
    println("done with " + x)
    ko(x)
  }

  println("Running A Sample Of Regression Tests")
  Fragments.foreach(1 to 20) { i => "Longtest" ! longTest(i.toString) ^ br }
}
```

Note that I am not overriding `def is`. If you do that in a mutable specification you will lose the `unbatched` argument at the beginning of the specification.

**Comment by Shadowfiend** [comment] 2017-02-22 15:58
Any chance you could publish that snapshot against Scala 2.11? We're still in mid-2016-land :)

**Comment by etorreborre** [comment] 2017-02-22 16:30
[Done](https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-core_2.11/3.8.8-20170222075022-d6a08b0).

**Comment by beaushinkle** [comment] 2017-02-23 14:30
Awesome - works as advertised. Thanks!

**Comment by etorreborre** [comment] 2017-02-23 15:02
Great I'm closing.

**Closed by etorreborre** 2017-02-23 15:02 UTC
