### ISSUE TITLE
ClassNotFoundException using specs2.run on Specifications that are in main (not test) scope

### ISSUE THREAD

**Issue by kolia** [etorreborre/specs2#422] opened 2015-10-06 13:32 UTC
```
STACKTRACE
  java.net.URLClassLoader$1.run(URLClassLoader.java:372)
  java.net.URLClassLoader$1.run(URLClassLoader.java:361)
  java.security.AccessController.doPrivileged(Native Method)
  java.net.URLClassLoader.findClass(URLClassLoader.java:360)
  java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
  java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  org.specs2.reflect.Classes$$anonfun$loadClassEither$1.apply(Classes.scala:134)
  org.specs2.reflect.Classes$$anonfun$loadClassEither$1.apply(Classes.scala:134)
  org.specs2.control.ActionT$$anonfun$safe$1.apply(ActionT.scala:89)
  org.specs2.control.ActionT$$anonfun$reader$1$$anonfun$apply$6.apply(ActionT.scala:80)
  org.specs2.control.Status$.safe(Status.scala:100)
  org.specs2.control.StatusT$$anonfun$safe$1.apply(StatusT.scala:62)
  org.specs2.control.StatusT$$anonfun$safe$1.apply(StatusT.scala:62)
  scalaz.syntax.ToApplicativeOps$$anon$1.self$lzycompute(ApplicativeSyntax.scala:29)
  scalaz.syntax.ToApplicativeOps$$anon$1.self(ApplicativeSyntax.scala:29)
  scalaz.syntax.ToApplicativeOps$ApplicativeIdV$$anonfun$point$1.apply(ApplicativeSyntax.scala:33)
  scalaz.WriterTApplicative$$anonfun$point$1.apply(WriterT.scala:268)
  scalaz.WriterTApplicative$$anonfun$point$1.apply(WriterT.scala:268)
  scalaz.effect.IO$$anonfun$apply$19$$anonfun$apply$20.apply(IO.scala:136)
  scalaz.effect.IO$$anonfun$apply$19$$anonfun$apply$20.apply(IO.scala:136)
  scalaz.FreeFunctions$$anonfun$return_$1.apply(Free.scala:326)
  scalaz.FreeFunctions$$anonfun$return_$1.apply(Free.scala:326)
  scalaz.std.FunctionInstances$$anon$1$$anonfun$map$1.apply(Function.scala:56)
  scalaz.Free$$anonfun$run$1.apply(Free.scala:172)
  scalaz.Free$$anonfun$run$1.apply(Free.scala:172)
  scalaz.Free.go2$1(Free.scala:119)
  scalaz.Free.go(Free.scala:122)
  scalaz.Free.run(Free.scala:172)
  scalaz.effect.IO$class.unsafePerformIO(IO.scala:22)
  scalaz.effect.IOFunctions$$anon$6.unsafePerformIO(IO.scala:227)
  org.specs2.runner.Runner$.execute(Runner.scala:29)
  org.specs2.runner.ClassRunner$class.run(ClassRunner.scala:43)
  specs2.run$.run(run.scala:12)
  specs2.run$.main(run.scala:27)
  specs2.run.main(run.scala)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:483)
  scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
  scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)

This looks like a specs2 exception...
Please report it with the preceding stacktrace at http://github.com/etorreborre/specs2/issues
```

## Context:

I am using maven with the maven-shade-plugin to pull in dependencies and produce a fat jar.  The specification itself is defined in the main scope (not in test scope).  I am running these tests by doing:

```bash
java -cp component-test/target/my-fat.jar specs2.run com.mycompany.ComponentSpecification
```

`ComponentSpecification` just pulls in a bunch of other Specs defined in traits in other modules, where they are also defined in the main scope, like so:

```scala
class ComponentsSpecification extends
LoaderSpecification with
SinkSpecification with
ConfigLoaderSpecification with
ConfigRepoSpecification with
SourceSpecification with
FramerSpecification {}
```

This error occurs AFTER some of the tests have run (I put some `println`s in the tests and they get run), so `ComponentsSpecification` is being loaded at some point, but some other classloader cannot retrieve it later on.

Also, this setup was working fine until I made some modifications inside some of the examples in `SinkSpecification`.  If I remove `SinkSpecification` from the list of traits that mix into `ComponentsSpecification`, the runner's classloader can find `ComponentsSpecification` and the tests run fine.

This is using `specs2-core_2.10` version 3.3.1

**Comment by kolia** [comment] 2015-10-06 14:30
Tried using `specs2_2.10` version 2.4.17

I get the same issue, with a longer stack trace so I can see what line in my code is offending.  It turns out that what breaks things is making some fields in the Specification traits private.  Maybe I am not understanding something about how scala trait private fields get serialized?

**Comment by etorreborre** [comment] 2015-10-06 21:43
I don't know exactly but errors like that are generally caused by the initialisation order of classes members. Setting those members as `lazy val` very often fixes the problem but I've never seen it fixed by just setting a member `private`.

Maybe a different design of your specifications would be possible, using links or tags to organize them.

**Comment by etorreborre** [comment] 2015-10-11 05:14
Did you make any progress on this issue? If not, can you create a small Github project reproducing the problem? Thanks.

**Comment by kolia** [comment] 2015-10-11 15:12
I ended up placing all my specs in main scope instead of test, and made the
runner be an app that calls specs2.run, and that's been working fine.  So I
have nothing in test scope.  This actually makes some sense in my context,
because I'm also trying to test the interoperability of components that are
defined in different modules, where the components are not all known in
advance (components are loaded via ServiceProviderInterface, anybody can
have added their own component in their own module before testing its
interoperability with others).  So I am happy with the current testing app
setup, it seems robust to allowing anyone add their own components, they
won't need to worry about whether or not their members are lazy, etc.  Is
there another way you'd suggest organizing tests in such a context?

That being said, I could try to put together a minimal gitub project to
reproduce the errors if you think that would be worth your time, otherwise
as I said, I am happy with the solution I've converged to.

Thanks!
Kolia

**Comment by etorreborre** [comment] 2015-10-11 21:19
I think I understand that some classes were not found because they were not all placed in the same scope. This is probably more of a sbt issue than a specs2 one. In case this helps in the future there are ways to declare sbt dependencies in order to have some main classes depend on test classes by adding "classifiers" to your dependency declaration:
```
% "compile->test"
```
Maybe it is also possible to do the same thing the other way around `% "test->compile"` and achieve what you need.

In any case I am glad you solved your issue!

**Closed by etorreborre** 2015-10-11 21:19 UTC
