### ISSUE TITLE
Sequentials pre-runs a property several times when set is used in ScalaCheck

### ISSUE THREAD

**Issue by juanrh** [etorreborre/specs2#393] opened 2015-07-13 17:53 UTC
Hi, this problem is similar to #86 but a bit different. With the following code: 

```scala
import org.junit.runner.RunWith
import org.specs2.runner.JUnitRunner
import org.specs2.ScalaCheck
import org.specs2.scalacheck.{Parameters, ScalaCheckProperty}
import org.scalacheck.{Prop, Gen}
import org.scalacheck.Arbitrary.arbitrary
import org.scalacheck.Prop.AnyOperators

import org.specs2.specification.BeforeAfterEach

@RunWith(classOf[JUnitRunner])
class SequentialScalacheck extends org.specs2.Specification 
                     with org.specs2.matcher.MustThrownExpectations
 					 with BeforeAfterEach
					 with ScalaCheck {
  def is = 
   sequential ^
   "Example run should be sequential with ScalaCheck configured for one worker" ^
     "property 1"  ! prop1 ^ 
     "property 2"  ! prop2 ^
     end
    
  var counters = scala.collection.mutable.Map("example" -> 0, "test case" -> 0, "prop1" -> 0)
  
  def enter(counterId : String) : Unit = this.synchronized {
    println(s"one more $counterId")
    counters(counterId) = counters(counterId) + 1
    if (counters(counterId) > 1) {
      println(s"too many $counterId")
      throw new RuntimeException("this should be sequential")
    }
  }
  
  def exit(counterId : String) : Unit = this.synchronized { 
    println(s"one less $counterId")
    counters(counterId) -= 1
  }
  
  var once = false
  def enterOnce() : Unit = this.synchronized {
    if (once) {
      throw new RuntimeException("this should be executed just once")
    }
    once = true
  }
  
  override def before : Unit = enter("example")
  override def after : Unit = exit("example")
  
  def prop1 = {
    enter("prop1") 
    enterOnce()
    val p = 
      Prop.forAll ("x" |: Gen.choose(0, 100)) { x : Int => 
        print(s"$x,")
        enter("test case")
        x must be_>=(0)
        exit("test case")
        true
    } . set(workers = 1, minTestsOk = 150).verbose // comment the set and this works ok
   exit("prop1")
   p
  }
  
  def prop2 = {
    println("running prop2")
    2 === 2
  }
}
```
The RuntimeException("this should be executed just once") is thrown because prop1 is executed more than once. What I find more surprising is that when . set(workers = 1, minTestsOk = 150).verbose is commented this works ok. Also, if we comment  enterOnce() and uncomment . set(workers = 1, minTestsOk = 150).verbose then this runs ok, and it seems that prop1 is somewhat "pre-run" 2 times and then it runs completely

one more example
one more prop1
one less prop1
one more prop1
one less prop1
one more prop1
one less prop1
95,one more test case
one less test case
77,one more test case
....

This is a problem because it makes very difficult to use BeforeAfterEach or even BeforeAfterAll, anyway is a surprising behaviour to me. Am I doing something wrong?

Thanks a lot for your help

**Comment by etorreborre** [comment] 2015-07-13 22:34
I am going to have a look at that. At first it seems like an issue with an implicit conversion that is independent of `Before/After`. Try the following:
```
import org.specs2.execute._

def prop1 = {
    enter("prop1") 
    enterOnce()
    val p = AsResult {
      Prop.forAll ("x" |: Gen.choose(0, 100)) { x : Int => 
        print(s"$x,")
        enter("test case")
        x must be_>=(0)
        exit("test case")
        true
     } . set(workers = 1, minTestsOk = 150).verbose // comment the set and this works ok
   }
   exit("prop1")
   p
  }
```

**Comment by etorreborre** [comment] 2015-07-14 04:22
I think the repeated evaluation issue is fixed in [`specs2-scalacheck_2.11-3.6.2-20150714025313-9b19fc6`](https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-scalacheck_2.11/3.6.2-20150714025313-9b19fc6). Can you please re-test your code with this jar?

**Comment by juanrh** [comment] 2015-07-14 09:39
Thank you so much for the quick response, that worked like a charm!

**Comment by juanrh** [comment] 2015-07-14 09:55
Hi, I'm using Scala 2.10.5 because I have Spark as my main dependency and the support for Scala 2.11 in Spark it's still experimental. So I have tried with 

libraryDependencies += "org.specs2" %% "specs2-scalacheck" % "3.6.2-20150703053452-023900f"

in sbt, which is the closest dependency that I have found at https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-scalacheck_2.10/. The program seems to behave the same with the new dependency

**Comment by etorreborre** [comment] 2015-07-14 11:48
Ok, please try the [scala 2.10 version](https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-scalacheck_2.10/3.6.2-20150714111537-9b1ffcc/) instead.

**Comment by juanrh** [comment] 2015-07-14 18:47
Hi, I have tried with that version and the code behaves the same: when set(workers = 1, minTestOk = 150) is uncommented activate and enterOnce() is commented I can see that prop1 is started to be executed 3 times, and so when enterOnce() is uncommented then the execption is thrown

**Comment by etorreborre** [comment] 2015-07-14 22:00
Please check again the version numbers and classpath for 2.10 because I don't see why the behaviour under 2.10 would be different to 2.11.

**Comment by juanrh** [comment] 2015-07-16 08:55
Hi, 

I've tried again and it keeps failing. I've setup a build in travis-ci so it is not dependent on my environment. The github repo being used is https://github.com/juanrh/sscheck and in https://github.com/juanrh/sscheck/blob/master/build.sbt I use

```scala
// lazy val specs2Version = "3.6.2" 
lazy val specs2Version = "3.6.2-20150714111537-9b1ffcc"

libraryDependencies += "org.specs2" %% "specs2-core" % specs2Version

libraryDependencies += "org.specs2" %% "specs2-core" % specs2Version 

libraryDependencies += "org.specs2" %% "specs2-scalacheck" % specs2Version

libraryDependencies += "org.specs2" %% "specs2-matcher-extra" % specs2Version

libraryDependencies += "org.specs2" %% "specs2-junit" % specs2Version 
```

In https://api.travis-ci.org/jobs/71216291/log.txt?deansi=true you can see the log of the travis job:

```
one more example
one more prop1
one less prop1
one more prop1
one less example
one more example
running prop2
one less example
[error] ! property 1
[error]  this should be executed just once (SequentialScalacheckOriginal.scala:44)
[error] es.ucm.fdi.sscheck.testing.SequentialScalacheckOriginal.enterOnce(SequentialScalacheckOriginal.scala:44)
[error] es.ucm.fdi.sscheck.testing.SequentialScalacheckOriginal.prop1(SequentialScalacheckOriginal.scala:54)
[error] es.ucm.fdi.sscheck.testing.SequentialScalacheckOriginal$$anonfun$is$1.apply(SequentialScalacheckOriginal.scala:21)
[error] es.ucm.fdi.sscheck.testing.SequentialScalacheckOriginal$$anonfun$is$1.apply(SequentialScalacheckOriginal.scala:21)
[info] SequentialScalacheckOriginalExample run should be sequential with ScalaCheck configured for one worker+ property 2
[info] 
[info] Total for specification SequentialScalacheckOriginal
[info] Finished in 7 ms
[info] 2 examples, 0 failure, 1 error
```

corresponding to an exception for the example above, that I've put in https://github.com/juanrh/sscheck/blob/master/src/test/scala/es/ucm/fdi/sscheck/testing/SequentialScalacheckOriginal.scala

**Comment by etorreborre** [comment] 2015-07-16 12:32
Ok, thanks for the github project. I think I know what the problem is, a new jar is on the way.

**Comment by etorreborre** [comment] 2015-07-16 13:02
Here it is. Try `3.6.2-20150716123420-ac2f605` (I tested it on your project, it works for me).

**Comment by etorreborre** [comment] 2015-07-16 13:03
BTW the difference between 2.10 and 2.11 comes from the implicits which are invoked to transform a Property in a Result. I had fixed one implicit but not the other one.

**Closed by etorreborre** 2015-07-16 13:03 UTC

**Comment by juanrh** [comment] 2015-07-16 14:49
Nice! I have tried it too and it works ok both in local and in Travis.

Thanks a lot for the quick response and perseverance!
