### ISSUE TITLE
Autoexamples do not respect newlines when exported as HTML

### ISSUE THREAD

**Issue by SemanticBeeng** [etorreborre/specs2#497] opened 2016-07-31 14:34 UTC
Trying to create a Specification that is both
1. a Spec with sections of code to be verified
2. a UserGuidePage in the sense that it renders HTML

The end goal is to reproduce this [blog post](http://archive.is/KxWQi) in Specs2.

In [this commit](https://github.com/SemanticBeeng/fpinscalabe/commit/2ec40b142103d2e3c86b2f73a41ad2ad5d44e74a) there is code to reproduce.

The problems areas are pieces of ${code}. $snippet{}-s are rendered fine as HTML.

The focus is [this file](https://github.com/SemanticBeeng/fpinscalabe/blob/2ec40b142103d2e3c86b2f73a41ad2ad5d44e74a/main/src/main/scala/org/fp/studies/kleisli/composition/Spec5.scala#L63-L80).

At this time it looks like the generated HTML contains incorrect sections.

![specs2 issue1](https://cloud.githubusercontent.com/assets/9296536/17277172/3569ace8-570a-11e6-8f0f-b0040cd417f6.gif)

At first I thought it is just the ul/li that is corrupt but then noticed that the inside code is also bad.

This is an improved version after manually fixing the "<ul><li>" that was generated quoted.

![specs2 issue2](https://cloud.githubusercontent.com/assets/9296536/17277198/04d1e978-570b-11e6-9995-0590c85b38ae.gif)

But the code inside is also generated HTML quoted so the issues is not in the surrounding tags.

Given that the actual code is there makes me think that it is properly extracted but the rendering part runs into an issue.

Will iterate to narrow it down.

**Comment by SemanticBeeng** [comment] 2016-07-31 20:46
@etorreborre : this [version](https://github.com/SemanticBeeng/fpinscalabe/commit/4b7736dd2f4abc075709661b8141e324b5d86e7e) uses $snippet-s and HTML renders nicely

![specs2 issue3](https://cloud.githubusercontent.com/assets/9296536/17279231/3c198ddc-573d-11e6-977e-541c0cf15607.gif)

Like you said, Snippets has [def checkOk](https://github.com/etorreborre/specs2/blob/454b3584b354ebd38cc73a1a183817f491e2cbd2/common/src/main/scala/org/specs2/execute/Snippets.scala#L47)` which gets the result of evaluating $snippets.

All together this makes me think $snippet is what I need, $snippet is powerful enough to cover and exceed what ${code} does.

So I am wondering what is the point of using ${code} ?

Please provide feedback on this train of thought.

**Comment by etorreborre** [comment] 2016-07-31 20:50
`${code}` was mostly intended for simple one-liners in specifications rendered in the console. It requires less braces and code than snippets. But for documentation I must say that I have always used snippets.

Fixes issues is always good though so if we can reduce and fix that one, that would be great.

**Comment by SemanticBeeng** [comment] 2016-07-31 20:58
You mean make ${...} work like $snippet(code ${code})? :-)On July 31, 2016 at 4:50 PM Eric Torreborre <notifications@github.com> wrote:${code} was mostly intended for simple one-liners in specifications rendered in the console. It requires less braces and code than snippets. But for documentation I must say that I have always used snippets.Fixes issues is always good though so if we can reduce and fix that one, that would be great.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by SemanticBeeng** [comment] 2016-07-31 21:00
... or just fix the rendering issue?
If you think it is a bug and that the way I wrote the spec should render fine then I will look into it.

**Comment by etorreborre** [comment] 2016-08-01 14:11
I want `${...}` to work differently than `$snippet` because I don't want to have to add `snippet` to every line of code in some specs. This is why the implementation is different. But I still don't know why the rendering doesn't work. If you could reduce it to a small example that I can reproduce it would be nice. For example this renders ok
```scala
class TestSpec extends Specification with ScalaCheck { def is = s2"""

  XXXX
  test $ok:
    ${
     /** [[Scala]] */

     val f = (i: Int) => i + 1
     f(1) must_== 1

    }

"""
}
```

**Comment by etorreborre** [comment] 2016-08-29 07:46
@SemanticBeeng where do we stand on this issue now?

**Comment by SemanticBeeng** [comment] 2016-08-29 08:06
@etorreborre My goal is to push the envelope of specs2 as a tool to create literate programming style documentation and it works very nicely: https://github.com/SemanticBeeng/fpinscalabe/blob/master/guide/src/test/scala/org/specs2/thirdparty/presentations/flatten_your_code/basics/Part07.scala 

Ran into this formatting issue in the process but since you showed the $snippet verification this alleged defect it is not in my way anymore.

I did encounter other formatting issues of Specs. UserGuidePage-es work fine. As such, 

1. it is possible this is not an actual defect but a misuse
2. to troubleshoot best I must find other occurrences in my work

If you hate this being an open defect then close it and I will reopen if/when confirmed as actual defect.

**Comment by etorreborre** [comment] 2016-08-29 08:07
Ok, please reopen with a small reproducible test-case when you have one.

**Comment by SemanticBeeng** [comment] 2016-08-29 08:16
Quick check off the top of your head: any obvious reason why https://github.com/SemanticBeeng/fpinscalabe/blob/97f5cc4987cbfe5ba8599964f9c8f15acff6b4b8/main/src/main/scala/org/fp/studies/fp/package.scala

would render like this
![disjunction](https://cloud.githubusercontent.com/assets/9296536/18045121/357280ce-6d9f-11e6-85dc-c9034ed3fbb0.gif)

when $link-ed to from the `UserGuide`?
![userguide](https://cloud.githubusercontent.com/assets/9296536/18045135/43d332f8-6d9f-11e6-97c8-8b36d7c91560.gif)

**Comment by etorreborre** [comment] 2016-08-29 08:21
I don't know, it looks like the `stripMargin` didn't work. Maybe it doesn't work with `s2`?

**Comment by SemanticBeeng** [comment] 2016-08-29 08:23
My thinking/approach is to create full specs which render to HTML just like a `UserGuidePage` and then $link to such specs.

Is there anything in the design that forbids this?
Asking because you usually include specs in the `UserGuidePage`-s themselves.
But I'd like to have full/extensive specs done separately.

Please advise if the design should allow this.
I will look from there.

**Comment by SemanticBeeng** [comment] 2016-08-29 08:29
Indeed `stripMargin` may have a hand in this.
Removing by hand made the text look better but then I run into the previous formatting.

![disjunction](https://cloud.githubusercontent.com/assets/9296536/18045524/30a93d10-6da1-11e6-8148-3ec159f24cab.gif)

**Comment by SemanticBeeng** [comment] 2016-08-30 12:13
@etorreborre indeed seems like I am trying to use it other than designed.
It works for immutable specs that define "def is=" but not for mutable specs.

This works: https://github.com/SemanticBeeng/fpinscalabe/commit/9b6627861805e06945c7a85898927045547c052a

This gives bad HTML
https://github.com/SemanticBeeng/fpinscalabe/commit/5571bc4bf890740ede22af41f6c2be7173c50096
![specs2 issue](https://cloud.githubusercontent.com/assets/9296536/18088515/26285d24-6e89-11e6-862a-77ae511ad574.gif)

At this point I could use some insights from you about how deep this would go.

Seems that the HTML generation works for static/immutable specs because they can be interpreted statically but the mutable ones would have to be ran to determine their output.

scala-virtualized can be used to generate JavaScript at runtime: http://archive.is/DexiJ
Is this on the right path?

**Comment by etorreborre** [comment] 2016-08-30 15:14
@SemanticBeeng I'm not sure I understand the issue here.

In your first example you are extending `mutable.Specification` and you shouldn't override `def is` in that case. You should also not need to mix-in `AutoExamples` or `TextDsl` because they are already mixed-in.

Then when I run your second example I get a proper HTML page:
![image](https://cloud.githubusercontent.com/assets/10988/18094825/151a6904-6ed5-11e6-800b-504625ea7358.png)

So something must be different in my case. The ideal would be if you could package the issue as a small reproducible project for me to investigate.

**Comment by SemanticBeeng** [comment] 2016-09-03 15:16
@etorreborre I reproduced it easily but it is so easy that makes me think the cause is in my environment.

https://github.com/SemanticBeeng/specs2/commit/9ace0483b740e2f5a971b1cbb7cb8f51baa3b17b

![specs2 issue](https://cloud.githubusercontent.com/assets/9296536/18225718/a7604884-71c7-11e6-8e30-1e94e9e79a37.gif)

![specs2 issue1](https://cloud.githubusercontent.com/assets/9296536/18225722/ac51e71c-71c7-11e6-90db-91c9541a4e8e.gif)

![specs2 issue2](https://cloud.githubusercontent.com/assets/9296536/18225724/c9587a1a-71c7-11e6-8911-2904d9206613.gif)

**Comment by etorreborre** [comment] 2016-09-03 20:31
For what it's worth I have a more recent version of `pandoc`: `1.15.2.1`. Maybe you can try to upgrade your version?

**Comment by SemanticBeeng** [comment] 2016-09-04 04:41
Will do.
So this generates good HTML for you?
$ ./sbt
project guide
generate-website

**Comment by SemanticBeeng** [comment] 2016-09-04 05:28
How do I generate the site markdown only? And where is it generated?
Thinking to compare markdown first.

**Comment by etorreborre** [comment] 2016-09-04 07:25
By "incorrectly" you mean all the code is generated on one line, right?

**Comment by SemanticBeeng** [comment] 2016-09-04 07:41
yes

**Comment by SemanticBeeng** [comment] 2016-09-04 21:02
Seems that mutable Specs do not render well.

See 
https://github.com/SemanticBeeng/fpinscalabe/commit/10a0880ffdc502659a21dc4130afbe7b7d970eab
vs
https://github.com/SemanticBeeng/fpinscalabe/commit/37ca92dbe7244219f327a22610300568aadc111f

Notice how the `incl`-uded part renders well but the body of the immutable specs render badly.
On the other hand, the $snippets from includes are not validated (expected).

![specs2 issue1](https://cloud.githubusercontent.com/assets/9296536/18233830/853f29ec-72c0-11e6-86b0-b937e1443975.gif)

In the first commit the Spec is immutable and renders well.

Is this observation wrong in some way that I miss?

**Comment by etorreborre** [comment] 2016-09-05 07:27
Hi Nick,

A few things are intertwined here:

 - if you indent any text in a markdown document with more than 4 spaces it is interpreted as code. I think this is why some of your specs don't render ok even with immutable specs

 - I think there is indeed a problem with "auto-examples" spanning several lines. They get generated on one line. I tried to fix but nothing really worked. I'll have another look later on this week. 

I guess this means that you should restrict yourself to using snippets if you want to generate HTML docs at the moment.

BTW you can use the `html.nostats` option to remove the stats table in your generated html pages.

**Comment by etorreborre** [comment] 2016-09-05 07:28
I changed the description of the issue to be more specific. Let's try to focus each issue on a specific problem.

**Comment by SemanticBeeng** [comment] 2016-09-08 05:57
Hi Eric, 
I replaced `eg {` with `snippet {` in here https://github.com/SemanticBeeng/fpinscalabe/commit/753d2b8f22eed8a706a56ea01b68697e30f85a11

and it renders like

![specs2 issue3](https://cloud.githubusercontent.com/assets/9296536/18338381/32f68498-7566-11e6-919d-83d6c9ed4d5c.gif)

I could turn it all in an `s2` template like in the cases (I think).
But wondering if this is supposed to working.

In `specs2` I found only `SnippetsScriptSpec` somewhat close to what  did but ... not really. You seem to use `$snippet` inside `s2` templates.

Please advise if this is an issue to open separately.

Where would the issue be? `S2Macro`?

![specs2 issue3](https://cloud.githubusercontent.com/assets/9296536/18338519/858cb258-7567-11e6-8bf6-b990c8057cb3.gif)

**Comment by etorreborre** [comment] 2016-09-08 06:18
Yes I think this should be a separate issue with a title like "snippets in mutable specifications do not render text properly" and a boiled-down example showing how to reproduce the issue independently from your project. I will try to at least diagnose it today, thanks.

**Comment by etorreborre** [comment] 2016-09-08 06:30
Sorry, I read things wrong. Actually snippets have not been created to work with mutable specifications. So if you invoke `snippet` in a mutable specification it doesn't get translated to a `Fragment` and added to the spec. It is debatable if his should be done or not. What would snippets in a mutable spec bring that you cannot have with an immutable spec?

**Comment by SemanticBeeng** [comment] 2016-09-08 06:56
Hmm... still not there in understanding the complete distinction between the semantics of mutable vs immutable.

Tried to make the spec (above) immutable but had to add `TextDSL` because of the calls to `p`.
Now I am getting this:

![specs2 issue3](https://cloud.githubusercontent.com/assets/9296536/18339674/ea291c90-756e-11e6-9716-91f28ff91ae8.gif)

which I got before and did not understand,
So now will have to put everything under `s2`  and `${snippet{` in an immutable spec.

But then it is not clear what the semantic difference would be with `eg`.
I guess that is another way to ask "What would snippets in a mutable spec bring that you cannot have with an immutable spec?".

Then how should I think about the utility of `eg` vs verified `snippet`s?

**Comment by etorreborre** [comment] 2016-09-08 07:42
Mutable specifications are a variation on immutable ones. An immutable specification is more or less a class with a `is` method returning a list of fragments. 

A mutable one adds a bit more DSL and a mutable variable to store fragments that are created in the body of the class. So when you write
```scala
"this is some text".p
```

The `.p` method takes care of updating that mutable variable for you with a new `Text` fragment. But it does not make sense to mix that mutable DSL to an immutable specification where you can put any text you want in the `s2` interpolated string.

So for "literate specifications" I would advise to only use `s2` strings and `snippets`. `eg` methods can be left to small specifications where you don't have a better text than the code itself to describe an example:
```scala
eg { (1 must be_==(2)) returns "1 is not equal to 2" }
```
Instead of writing 
```scala
"A comparison with 2 different values returns a failure message" >> { 
  (1 must be_==(2)) returns "1 is not equal to 2"
}
```

**Comment by SemanticBeeng** [comment] 2016-09-08 08:35
Thanks, Eric. That explanation clarifies the example you gave,
But I am trying to reconcile these differences at the implementation level.

In my mind a `snippet` should be treated the same everywhere.
Cannot imagine a good reason why it have a different handling in a `mutable` spec vs in an `immutable` spec

Thinking all specs should be interpreted the same regardless of mutable or not.

When I say interpreted I mean both 
1. execution / verification
2. rendering to markdown 

After all, the semantics of a spec in the above definition should not be influenced by how it was created.

There should be a common interpreter that traverses the spec structure and generates fragments for execution an another one for rendering.

Where am I wrong in the above?

BTW: how render all errors from the execution interpretation :-)

![specs2 issue3](https://cloud.githubusercontent.com/assets/9296536/18342563/6f1702ec-757d-11e6-91d4-44ac84546f20.gif)

**Comment by etorreborre** [comment] 2016-09-08 09:52
In principle I agree, but there are different levels here. `snippet` does not do anything else than creating a snippet of code. Then the `Snippets` trait provides implicit methods to allow those snippets to be added to an immutable spec. But there is not similar trait for a mutable spec. One should be added in order to be able to use snippets with mutable specs.

**Comment by etorreborre** [comment] 2016-09-08 09:54
For your check you might have to do this:
```scala
check {
  (thruthyIf(...) must_== ...) and
  (thruthyIf(...) must_== ...) and
  (thruthyIf(...) must_== ...)
}
```
Or mix-in the `AllExpectations` trait and write:
```scala
check {
  thruthyIf(...) must_== ...
  thruthyIf(...) must_== ...
  thruthyIf(...) must_== ...
}
```

**Comment by etorreborre** [comment] 2016-11-17 07:17
I am closing this for now. Let's reopen specific issues if there are some.

**Closed by etorreborre** 2016-11-17 07:17 UTC
