### ISSUE TITLE
False method verification when method declaration contains default values

### ISSUE THREAD

**Issue by daliuss** [etorreborre/specs2#411] opened 2015-09-08 15:35 UTC
```scala
import org.specs2.mock.Mockito
import org.specs2.mutable.SpecificationWithJUnit
import org.specs2.specification.Scope

class Specs2MatcherIssue extends SpecificationWithJUnit with Mockito {

  class TargetClass {
    def method(p1: String, p2: String = "") = p1
  }

  "Invocation verification should fail" in new Scope {
    val target = mock[TargetClass]

    target.method("val")

    got {
      one(target).method(p1 = "") // This passes
    }
  }
}
```

Mockito 1.9.5
Specs2 3.6.1

**Comment by etorreborre** [comment] 2015-09-08 22:55
There's not much I can do here. The issue is how Scala translate method calls when there are default arguments
```
// without default values
((IssueSpec.TargetClass)org.mockito.Mockito.verify(target)).method("blah", "other")

// with default values
IssueSpec.TargetClass qual$1 = (IssueSpec.TargetClass)org.mockito.Mockito.verify(target); String x$1 = "blah"; String x$2 = qual$1.method$default$2(); return qual$1.method(x$1, x$2)
```

As you can see in the second case `verify` doesn't verify much. The work around is to specify all the default values when using Mockito:
```
org.mockito.Mockito.verify(target).method("blah", "other")`
```
And even like this, the error message will be incomplete, mentioning `null` instead of `other`:
```
error] ! Invocation verification should fail
[error]  org.mockito.exceptions.verification.junit.ArgumentsAreDifferent:
[error]  Argument(s) are different! Wanted:
[error]  targetClass.method("blah", "other");
[error]  -> at user.IssueSpec$$anonfun$1.apply(TestSpec.scala:32)
[error]  Actual invocation has different arguments:
[error]  targetClass.method("val", null);
[error]  -> at user.IssueSpec$$anonfun$1.apply(TestSpec.scala:31) (NativeConstructorAccessorImpl.java:-2)
```

**Closed by etorreborre** 2015-09-08 22:55 UTC
